blank_issues_enabled: false
contact_links:
- name: 'General Question'
  url: https://stackoverflow.com/questions/tagged/wso2-streaming-integrator
  about: "If you have a question then please ask on Stack Overflow using the #wso2-streaming-integrator tag."
    Chat with the community to get quick clarifications for your questions.
